# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - build
  - package
  - deploy

# ----------------------------------------
# Build
# ----------------------------------------

build:
  stage: build
  image: ubuntu:latest
  script:
    - bash build/build.sh
  only: 
    - master
  artifacts:
    paths:
      - public/
    expire_in: 1 hour

# ----------------------------------------
# Package
# ----------------------------------------

package:
  stage: package
  image: alpine:latest
  script:
    - echo 'No action needed.'
  only: 
    - master
  artifacts:
    paths:
      - public
    expire_in: 4 weeks